/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package ch.psi.sics.hipadaba.validation;

import ch.psi.sics.hipadaba.SICS;

import commonj.sdo.Sequence;

import java.util.Map;

/**
 * A sample validator interface for {@link ch.psi.sics.hipadaba.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
	boolean validate();

	boolean validateMixed(Sequence value);
	boolean validateXMLNSPrefixMap(Map<String, String> value);
	boolean validateXSISchemaLocation(Map<String, String> value);
	boolean validateSICS(SICS value);
}
